cluster: "slurm-submit.py {dependencies}"
cluster-status: "slurm-status.py"  #not fully tested yet.. better to rely on filesystem checks..
cluster-cancel: "scancel"
jobscript: "slurm-jobscript.sh"
jobs: 500
latency-wait: 60
verbose: {{cookiecutter.verbose}}
use-singularity: {{cookiecutter.use_singularity}}
use-envmodules: {{cookiecutter.use_envmodules}}
singularity-args: '\-e'
immediate-submit: {{cookiecutter.immediate_submit}}
notemp: {{cookiecutter.immediate_submit}} #notemp set to the value of immediate_submit (since both have to be true together)
max-jobs-per-second: 2
max-status-checks-per-second: 1
restart-times: 1
local-cores: 1
#singularity-prefix: '/project/ctb-akhanf/akhanf/singularity/snakemake_containers'
rerun-incomplete: True
keep-going: True
show-failed-logs: True

cores: 32
resources: 'mem_mb=502000'
